# Generated by Django 6.0.3 on 2026-06-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('runs', models.IntegerField()),
                ('profile', models.URLField()),
                ('email', models.EmailField(max_length=250)),
                ('dob', models.DateField(blank=True)),
            ],
        ),
    ]
